export const CARD_KR_NAME_MAP: Record<string, string> = {
  NH_CARD: "농협카드",
  SHINHAN_CARD: "신한카드",
  KOOKMIN_CARD: "국민카드",
  HANA_CARD: "하나카드",
  HYUNDAI_CARD: "현대카드",
  LOTTE_CARD: "롯데카드",
  SAMSUNG_CARD: "삼성카드",
  WOORI_CARD: "우리카드",
  BC_CARD: "BC카드",
  TOSS_CARD: "토스카드",
  KAKAO_BANK: "카카오뱅크",
  IBK_BC: "IBK기업은행 BC카드",
  GWANGJU_BANK: "광주은행",
  KDB_BANK: "산업은행",
  SAEMAUL: "새마을금고",
  SHINHYEOP: "신협",
  CITI_CARD: "씨티카드",
  POST: "우체국카드",
  SAVINGS_BANK: "저축은행중앙회",
  JEONBUK_BANK: "전북은행",
  JEJU_BANK: "제주은행",
  KBANK: "케이뱅크",
  TOSSBANK: "토스뱅크",
  SUHYUP: "수협은행",
};
