export const COIN_PRICE = [
  {
    id: 1,
    coinAmount: 1,
    price: 550,
    coinExp: 30,
    isBgBlue: false,
  },
  {
    id: 2,
    coinAmount: 5,
    price: 2750,
    coinExp: 30,
    isBgBlue: false,
  },
  {
    id: 3,
    coinAmount: 10,
    price: 5500,
    coinExp: 30,
    isBgBlue: false,
  },
  {
    id: 4,
    coinAmount: 20,
    price: 11000,
    coinExp: 30,
    isBgBlue: false,
  },
  {
    id: 5,
    coinAmount: 30,
    price: 16500,
    coinExp: 30,
    isBgBlue: false,
  },
  {
    id: 6,
    coinAmount: 180,
    price: 99000,
    coinExp: 90,
    isBgBlue: true,
  },
  {
    id: 7,
    coinAmount: 300,
    price: 165000,
    coinExp: 180,
    isBgBlue: true,
  },
];

export const SUBSCRIBE_OPTION = [
  {
    id: 1,
    option_ko: "베이직",
    option_en: "Basic",
    coinAmount: 90,
    extroCoinAmount: null,
    totalCoinAmount: 90,
    price: 50000,
    recommendTarget: "1주일에 한 번 운동하는 사람",
    benefit: "X",
    comment: "가볍게 시작하기",
  },
  {
    id: 2,
    option_ko: "스탠다드",
    option_en: "Standard",
    coinAmount: 130,
    extroCoinAmount: 5,
    totalCoinAmount: 135,
    price: 70000,
    recommendTarget: "1주일에 2-3번 운동하는 사람",
    benefit: "추가 코인 제공",
    comment: "인기있는 요금제",
  },
  {
    id: 3,
    option_ko: "프로",
    option_en: "Pro",
    coinAmount: 190,
    extroCoinAmount: 10,
    totalCoinAmount: 200,
    price: 100000,
    recommendTarget: "1주일에 3-4번 운동하는 사람",
    benefit: "추가 코인 제공",
    comment: "최대 혜택 플랜",
  },
];
